application: imokdev
version: 2
runtime: python
api_version: 1

handlers:

- url: /static/css
  static_dir: static/css
  mime_type: text/css

- url: /static/js
  static_dir: static/js
  mime_type: text/javascript

- url: /static/img
  static_dir: static/img
  mime_type: image/png

- url: /static/pdf
  static_dir: static/pdf
  mime_type: application/pdf

- url: /static/blackberry/IMOk.jad
  static_files: static/blackberry/IMOk.jad
  mime_type: text/vnd.sun.j2me.app-descriptor
  upload: static/blackberry/IMOk.jad

- url: /static/blackberry/IMOk.cod
  static_files: static/blackberry/IMOk.cod
  mime_type: application/vnd.rim.cod
  upload: static/blackberry/IMOk.cod

- url: /bb.*
  script: blackberry.py

- url: /smsgateway/android/.*
  script: sms_android.py

- url: /smsgateway/twilio/.*
  script: sms_twilio.py

- url: /tasks/.*
  script: tasks.py
  login: admin

- url: /newuser/.*
  script: newuser.py

- url: /debug.*
  script: debug.py
  login: admin

- url: /data/.*
  script: browsedata.py
  login: admin

- url: /export.*
  script: export.py
  login: admin

- url: .*
  script: main.py
